/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedOrganizationsRouteImport } from './routes/_protected/organizations'
import { Route as ProtectedOrganizationRouteImport } from './routes/_protected/organization'
import { Route as ProtectedOrganizationIndexRouteImport } from './routes/_protected/organization.index'
import { Route as ProtectedOrganizationSlugRouteImport } from './routes/_protected/organization.$slug'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizationsRoute = ProtectedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationRoute = ProtectedOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationIndexRoute =
  ProtectedOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationRoute,
  } as any)
const ProtectedOrganizationSlugRoute =
  ProtectedOrganizationSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ProtectedOrganizationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/organization': typeof ProtectedOrganizationRouteWithChildren
  '/organizations': typeof ProtectedOrganizationsRoute
  '/organization/$slug': typeof ProtectedOrganizationSlugRoute
  '/organization/': typeof ProtectedOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/organizations': typeof ProtectedOrganizationsRoute
  '/organization/$slug': typeof ProtectedOrganizationSlugRoute
  '/organization': typeof ProtectedOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/sso-callback': typeof SsoCallbackRoute
  '/_protected/organization': typeof ProtectedOrganizationRouteWithChildren
  '/_protected/organizations': typeof ProtectedOrganizationsRoute
  '/_protected/organization/$slug': typeof ProtectedOrganizationSlugRoute
  '/_protected/organization/': typeof ProtectedOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sso-callback'
    | '/organization'
    | '/organizations'
    | '/organization/$slug'
    | '/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sso-callback'
    | '/organizations'
    | '/organization/$slug'
    | '/organization'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/sso-callback'
    | '/_protected/organization'
    | '/_protected/organizations'
    | '/_protected/organization/$slug'
    | '/_protected/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organizations': {
      id: '/_protected/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof ProtectedOrganizationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organization': {
      id: '/_protected/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof ProtectedOrganizationRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organization/': {
      id: '/_protected/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof ProtectedOrganizationIndexRouteImport
      parentRoute: typeof ProtectedOrganizationRoute
    }
    '/_protected/organization/$slug': {
      id: '/_protected/organization/$slug'
      path: '/$slug'
      fullPath: '/organization/$slug'
      preLoaderRoute: typeof ProtectedOrganizationSlugRouteImport
      parentRoute: typeof ProtectedOrganizationRoute
    }
  }
}

interface ProtectedOrganizationRouteChildren {
  ProtectedOrganizationSlugRoute: typeof ProtectedOrganizationSlugRoute
  ProtectedOrganizationIndexRoute: typeof ProtectedOrganizationIndexRoute
}

const ProtectedOrganizationRouteChildren: ProtectedOrganizationRouteChildren = {
  ProtectedOrganizationSlugRoute: ProtectedOrganizationSlugRoute,
  ProtectedOrganizationIndexRoute: ProtectedOrganizationIndexRoute,
}

const ProtectedOrganizationRouteWithChildren =
  ProtectedOrganizationRoute._addFileChildren(
    ProtectedOrganizationRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedOrganizationRoute: typeof ProtectedOrganizationRouteWithChildren
  ProtectedOrganizationsRoute: typeof ProtectedOrganizationsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedOrganizationRoute: ProtectedOrganizationRouteWithChildren,
  ProtectedOrganizationsRoute: ProtectedOrganizationsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
