/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSelectOrgRouteImport } from './routes/_protected/select-org'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ProtectedOrganizationOrgIdRouteImport } from './routes/_protected/organization.$orgId'
import { Route as ProtectedOrganizationOrgIdSettingsRouteImport } from './routes/_protected/organization_.$orgId.settings'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSelectOrgRoute = ProtectedSelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizationOrgIdRoute =
  ProtectedOrganizationOrgIdRouteImport.update({
    id: '/organization/$orgId',
    path: '/organization/$orgId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizationOrgIdSettingsRoute =
  ProtectedOrganizationOrgIdSettingsRouteImport.update({
    id: '/organization_/$orgId/settings',
    path: '/organization/$orgId/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/select-org': typeof ProtectedSelectOrgRoute
  '/organization/$orgId': typeof ProtectedOrganizationOrgIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/organization/$orgId/settings': typeof ProtectedOrganizationOrgIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/select-org': typeof ProtectedSelectOrgRoute
  '/organization/$orgId': typeof ProtectedOrganizationOrgIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/organization/$orgId/settings': typeof ProtectedOrganizationOrgIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/sso-callback': typeof SsoCallbackRoute
  '/_protected/select-org': typeof ProtectedSelectOrgRoute
  '/_protected/organization/$orgId': typeof ProtectedOrganizationOrgIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_protected/organization_/$orgId/settings': typeof ProtectedOrganizationOrgIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sso-callback'
    | '/select-org'
    | '/organization/$orgId'
    | '/api/trpc/$'
    | '/organization/$orgId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sso-callback'
    | '/select-org'
    | '/organization/$orgId'
    | '/api/trpc/$'
    | '/organization/$orgId/settings'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/sso-callback'
    | '/_protected/select-org'
    | '/_protected/organization/$orgId'
    | '/api/trpc/$'
    | '/_protected/organization_/$orgId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SsoCallbackRoute: typeof SsoCallbackRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/select-org': {
      id: '/_protected/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof ProtectedSelectOrgRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organization/$orgId': {
      id: '/_protected/organization/$orgId'
      path: '/organization/$orgId'
      fullPath: '/organization/$orgId'
      preLoaderRoute: typeof ProtectedOrganizationOrgIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organization_/$orgId/settings': {
      id: '/_protected/organization_/$orgId/settings'
      path: '/organization/$orgId/settings'
      fullPath: '/organization/$orgId/settings'
      preLoaderRoute: typeof ProtectedOrganizationOrgIdSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedSelectOrgRoute: typeof ProtectedSelectOrgRoute
  ProtectedOrganizationOrgIdRoute: typeof ProtectedOrganizationOrgIdRoute
  ProtectedOrganizationOrgIdSettingsRoute: typeof ProtectedOrganizationOrgIdSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSelectOrgRoute: ProtectedSelectOrgRoute,
  ProtectedOrganizationOrgIdRoute: ProtectedOrganizationOrgIdRoute,
  ProtectedOrganizationOrgIdSettingsRoute:
    ProtectedOrganizationOrgIdSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SsoCallbackRoute: SsoCallbackRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
